[2023-09-09T16:06:25.372+0000] {processor.py:153} INFO - Started process (PID=49) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:06:25.381+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:06:25.396+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:06:25.396+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:06:25.458+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:06:25.457+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:06:25.468+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:06:25.556+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.203 seconds
[2023-09-09T16:06:56.144+0000] {processor.py:153} INFO - Started process (PID=102) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:06:56.145+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:06:56.146+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:06:56.146+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:06:56.153+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:06:56.152+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:06:56.154+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:06:56.196+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.057 seconds
[2023-09-09T16:07:26.352+0000] {processor.py:153} INFO - Started process (PID=162) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:07:26.353+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:07:26.354+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:07:26.354+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:07:26.369+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:07:26.368+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:07:26.369+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:07:26.408+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.060 seconds
[2023-09-09T16:07:57.320+0000] {processor.py:153} INFO - Started process (PID=217) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:07:57.322+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:07:57.322+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:07:57.322+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:07:57.329+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:07:57.328+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:07:57.330+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:07:57.360+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.043 seconds
[2023-09-09T16:10:30.299+0000] {processor.py:153} INFO - Started process (PID=49) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:10:30.320+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:10:30.328+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:10:30.328+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:10:30.406+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:10:30.405+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:10:30.406+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:10:30.548+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.276 seconds
[2023-09-09T16:11:01.040+0000] {processor.py:153} INFO - Started process (PID=100) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:11:01.041+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:11:01.042+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:11:01.041+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:11:01.048+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:11:01.047+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:11:01.049+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:11:01.072+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T16:11:31.125+0000] {processor.py:153} INFO - Started process (PID=161) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:11:31.136+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:11:31.137+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:11:31.137+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:11:31.145+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:11:31.144+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:11:31.152+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:11:31.189+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.074 seconds
[2023-09-09T16:12:01.410+0000] {processor.py:153} INFO - Started process (PID=215) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:12:01.414+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:12:01.415+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:12:01.415+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:12:01.422+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:12:01.421+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:12:01.422+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:12:01.449+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.046 seconds
[2023-09-09T16:12:31.558+0000] {processor.py:153} INFO - Started process (PID=277) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:12:31.562+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:12:31.563+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:12:31.563+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:12:31.580+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:12:31.577+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:12:31.581+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:12:31.644+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.110 seconds
[2023-09-09T16:13:02.296+0000] {processor.py:153} INFO - Started process (PID=330) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:13:02.297+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:13:02.297+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:13:02.297+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:13:02.304+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:13:02.303+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:13:02.304+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:13:02.328+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T16:13:33.058+0000] {processor.py:153} INFO - Started process (PID=392) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:13:33.059+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:13:33.060+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:13:33.060+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:13:33.068+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:13:33.067+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:13:33.068+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:13:33.102+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.048 seconds
[2023-09-09T16:14:03.140+0000] {processor.py:153} INFO - Started process (PID=445) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:14:03.141+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:14:03.142+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:14:03.142+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:14:03.149+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:14:03.148+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:14:03.149+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:14:03.172+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:14:33.649+0000] {processor.py:153} INFO - Started process (PID=507) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:14:33.660+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:14:33.660+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:14:33.660+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:14:33.667+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:14:33.666+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:14:33.680+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:14:33.736+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.097 seconds
[2023-09-09T16:15:03.873+0000] {processor.py:153} INFO - Started process (PID=561) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:15:03.874+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:15:03.874+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:15:03.874+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:15:03.881+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:15:03.880+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:15:03.881+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:15:03.905+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T16:15:34.130+0000] {processor.py:153} INFO - Started process (PID=622) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:15:34.132+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:15:34.133+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:15:34.133+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:15:34.140+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:15:34.139+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:15:34.140+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:15:34.164+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.037 seconds
[2023-09-09T16:16:04.582+0000] {processor.py:153} INFO - Started process (PID=684) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:16:04.583+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:16:04.584+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:16:04.584+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:16:04.591+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:16:04.590+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:16:04.591+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:16:04.616+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.038 seconds
[2023-09-09T16:16:35.355+0000] {processor.py:153} INFO - Started process (PID=737) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:16:35.356+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:16:35.357+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:16:35.357+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:16:35.363+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:16:35.362+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:16:35.364+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:16:35.387+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:17:05.692+0000] {processor.py:153} INFO - Started process (PID=800) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:17:05.693+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:17:05.694+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:17:05.694+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:17:05.701+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:17:05.700+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:17:05.701+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:17:05.724+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T16:17:35.981+0000] {processor.py:153} INFO - Started process (PID=855) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:17:35.982+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:17:35.983+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:17:35.983+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:17:35.989+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:17:35.988+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:17:35.990+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:17:36.013+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T16:18:06.604+0000] {processor.py:153} INFO - Started process (PID=916) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:18:06.605+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:18:06.606+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:18:06.606+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:18:06.612+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:18:06.611+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:18:06.612+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:18:06.636+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.037 seconds
[2023-09-09T16:18:36.793+0000] {processor.py:153} INFO - Started process (PID=977) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:18:36.795+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:18:36.795+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:18:36.795+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:18:36.802+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:18:36.801+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:18:36.802+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:18:36.826+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.037 seconds
[2023-09-09T16:19:07.461+0000] {processor.py:153} INFO - Started process (PID=1032) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:19:07.463+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:19:07.464+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:19:07.464+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:19:07.471+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:19:07.470+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:19:07.472+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:19:07.499+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.046 seconds
[2023-09-09T16:19:37.555+0000] {processor.py:153} INFO - Started process (PID=1094) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:19:37.557+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:19:37.557+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:19:37.557+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:19:37.564+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:19:37.563+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:19:37.564+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:19:37.588+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.037 seconds
[2023-09-09T16:20:07.974+0000] {processor.py:153} INFO - Started process (PID=1148) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:20:07.976+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:20:07.977+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:20:07.976+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:20:07.983+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:20:07.982+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:20:07.983+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:20:08.007+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.037 seconds
[2023-09-09T16:20:38.740+0000] {processor.py:153} INFO - Started process (PID=1211) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:20:38.741+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:20:38.742+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:20:38.741+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:20:38.748+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:20:38.748+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:20:38.749+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:20:38.771+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:21:09.310+0000] {processor.py:153} INFO - Started process (PID=1265) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:21:09.312+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:21:09.313+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:21:09.313+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:21:09.320+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:21:09.319+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:21:09.320+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:21:09.343+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T16:21:39.611+0000] {processor.py:153} INFO - Started process (PID=1328) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:21:39.612+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:21:39.612+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:21:39.612+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:21:39.619+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:21:39.618+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:21:39.619+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:21:39.642+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:21:44.974+0000] {processor.py:153} INFO - Started process (PID=1343) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:21:44.980+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:21:44.981+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:21:44.981+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:21:44.999+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:21:44.998+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:21:45.000+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:21:45.038+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.068 seconds
[2023-09-09T16:22:15.428+0000] {processor.py:153} INFO - Started process (PID=1398) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:22:15.429+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:22:15.430+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:22:15.430+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:22:15.439+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:22:15.438+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:22:15.440+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:22:15.465+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.040 seconds
[2023-09-09T16:22:45.622+0000] {processor.py:153} INFO - Started process (PID=1459) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:22:45.623+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:22:45.624+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:22:45.624+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:22:45.632+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:22:45.631+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:22:45.632+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:22:45.656+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.038 seconds
[2023-09-09T16:23:16.164+0000] {processor.py:153} INFO - Started process (PID=1512) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:23:16.166+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:23:16.167+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:23:16.167+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:23:16.175+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:23:16.174+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:23:16.176+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:23:16.199+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.038 seconds
[2023-09-09T16:23:46.868+0000] {processor.py:153} INFO - Started process (PID=1575) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:23:46.871+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:23:46.872+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:23:46.872+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:23:46.886+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:23:46.878+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:23:46.888+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:23:46.929+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.071 seconds
[2023-09-09T16:24:17.175+0000] {processor.py:153} INFO - Started process (PID=1628) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:24:17.176+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:24:17.177+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:24:17.177+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:24:17.186+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:24:17.185+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:24:17.196+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:24:17.232+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.068 seconds
[2023-09-09T16:24:47.358+0000] {processor.py:153} INFO - Started process (PID=1691) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:24:47.359+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:24:47.359+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:24:47.359+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:24:47.366+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:24:47.365+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:24:47.366+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:24:47.388+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.034 seconds
[2023-09-09T16:25:17.543+0000] {processor.py:153} INFO - Started process (PID=1745) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:25:17.552+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:25:17.553+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:25:17.552+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:25:17.560+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:25:17.559+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:25:17.560+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:25:17.584+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.050 seconds
[2023-09-09T16:25:47.782+0000] {processor.py:153} INFO - Started process (PID=1806) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:25:47.783+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:25:47.784+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:25:47.784+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:25:47.790+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:25:47.789+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:25:47.791+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:25:47.815+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.037 seconds
[2023-09-09T16:26:17.897+0000] {processor.py:153} INFO - Started process (PID=1860) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:26:17.898+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:26:17.898+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:26:17.898+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:26:17.905+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:26:17.904+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:26:17.905+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:26:17.928+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:26:48.441+0000] {processor.py:153} INFO - Started process (PID=1921) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:26:48.442+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:26:48.443+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:26:48.443+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:26:48.449+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:26:48.448+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:26:48.450+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:26:48.473+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T16:27:19.462+0000] {processor.py:153} INFO - Started process (PID=1973) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:27:19.464+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:27:19.464+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:27:19.464+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:27:19.471+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:27:19.470+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:27:19.471+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:27:19.494+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T16:27:50.379+0000] {processor.py:153} INFO - Started process (PID=2033) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:27:50.384+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:27:50.388+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:27:50.388+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:27:50.397+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:27:50.396+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:27:50.402+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:27:50.445+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.070 seconds
[2023-09-09T16:28:20.836+0000] {processor.py:153} INFO - Started process (PID=2087) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:28:20.837+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:28:20.837+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:28:20.837+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:28:20.844+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:28:20.843+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:28:20.844+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:28:20.868+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T16:28:51.647+0000] {processor.py:153} INFO - Started process (PID=2149) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:28:51.648+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:28:51.649+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:28:51.648+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:28:51.655+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:28:51.654+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:28:51.655+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:28:51.678+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:29:21.872+0000] {processor.py:153} INFO - Started process (PID=2203) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:29:21.873+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:29:21.874+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:29:21.874+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:29:21.881+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:29:21.880+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:29:21.881+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:29:21.905+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.037 seconds
[2023-09-09T16:29:52.764+0000] {processor.py:153} INFO - Started process (PID=2266) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:29:52.765+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:29:52.766+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:29:52.766+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:29:52.772+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:29:52.771+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:29:52.773+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:29:52.796+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:30:23.426+0000] {processor.py:153} INFO - Started process (PID=2327) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:30:23.429+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:30:23.430+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:30:23.430+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:30:23.437+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:30:23.436+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:30:23.437+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:30:23.462+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.041 seconds
[2023-09-09T16:30:53.750+0000] {processor.py:153} INFO - Started process (PID=2383) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:30:53.751+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:30:53.752+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:30:53.752+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:30:53.759+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:30:53.758+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:30:53.759+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:30:53.781+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:31:24.041+0000] {processor.py:153} INFO - Started process (PID=2445) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:31:24.043+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:31:24.044+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:31:24.043+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:31:24.050+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:31:24.050+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:31:24.051+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:31:24.073+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:31:54.990+0000] {processor.py:153} INFO - Started process (PID=2498) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:31:54.994+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:31:54.995+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:31:54.995+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:31:55.002+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:31:55.001+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:31:55.003+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:31:55.027+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.041 seconds
[2023-09-09T16:32:25.906+0000] {processor.py:153} INFO - Started process (PID=2560) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:32:25.907+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:32:25.908+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:32:25.908+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:32:25.915+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:32:25.914+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:32:25.915+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:32:25.938+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T16:32:56.806+0000] {processor.py:153} INFO - Started process (PID=2623) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:32:56.809+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:32:56.809+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:32:56.809+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:32:56.816+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:32:56.815+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:32:56.817+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:32:56.840+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.037 seconds
[2023-09-09T16:33:27.161+0000] {processor.py:153} INFO - Started process (PID=2676) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:33:27.162+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:33:27.163+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:33:27.163+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:33:27.172+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:33:27.171+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:33:27.173+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:33:27.196+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.039 seconds
[2023-09-09T16:33:58.031+0000] {processor.py:153} INFO - Started process (PID=2739) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:33:58.033+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:33:58.033+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:33:58.033+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:33:58.041+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:33:58.040+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:33:58.042+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:33:58.065+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.038 seconds
[2023-09-09T16:34:28.732+0000] {processor.py:153} INFO - Started process (PID=2793) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:34:28.733+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:34:28.734+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:34:28.734+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:34:28.763+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:34:28.762+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:34:28.763+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:34:28.805+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.081 seconds
[2023-09-09T16:34:59.696+0000] {processor.py:153} INFO - Started process (PID=2854) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:34:59.697+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:34:59.698+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:34:59.697+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:34:59.704+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:34:59.704+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:34:59.705+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:34:59.728+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T16:35:30.262+0000] {processor.py:153} INFO - Started process (PID=2907) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:35:30.263+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:35:30.264+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:35:30.264+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:35:30.271+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:35:30.270+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:35:30.271+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:35:30.293+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.034 seconds
[2023-09-09T16:36:00.886+0000] {processor.py:153} INFO - Started process (PID=2969) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:36:00.887+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:36:00.888+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:36:00.888+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:36:00.894+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:36:00.893+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:36:00.895+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:36:00.918+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T16:36:31.147+0000] {processor.py:153} INFO - Started process (PID=3023) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:36:31.148+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:36:31.149+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:36:31.149+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:36:31.155+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:36:31.154+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:36:31.155+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:36:31.178+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.034 seconds
[2023-09-09T16:37:01.500+0000] {processor.py:153} INFO - Started process (PID=3085) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:37:01.504+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:37:01.505+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:37:01.505+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:37:01.520+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:37:01.511+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:37:01.521+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:37:01.559+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.067 seconds
[2023-09-09T16:37:31.647+0000] {processor.py:153} INFO - Started process (PID=3143) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:37:31.648+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:37:31.649+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:37:31.649+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:37:31.656+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:37:31.655+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:37:31.656+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:37:31.687+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.044 seconds
[2023-09-09T16:38:01.938+0000] {processor.py:153} INFO - Started process (PID=3199) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:38:01.940+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:38:01.940+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:38:01.940+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:38:01.947+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:38:01.946+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:38:01.947+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:38:01.971+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.037 seconds
[2023-09-09T16:38:32.813+0000] {processor.py:153} INFO - Started process (PID=3260) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:38:32.815+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:38:32.816+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:38:32.816+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:38:32.823+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:38:32.821+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:38:32.823+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:38:32.851+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.041 seconds
[2023-09-09T16:38:37.361+0000] {processor.py:153} INFO - Started process (PID=3266) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:38:37.362+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:38:37.363+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:38:37.363+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:38:37.370+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:38:37.369+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:38:37.370+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:38:37.393+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:39:07.632+0000] {processor.py:153} INFO - Started process (PID=3328) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:39:07.633+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:39:07.634+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:39:07.634+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:39:07.641+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:39:07.640+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:39:07.641+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:39:07.666+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.038 seconds
[2023-09-09T16:39:38.109+0000] {processor.py:153} INFO - Started process (PID=3381) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:39:38.110+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:39:38.111+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:39:38.111+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:39:38.117+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:39:38.117+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:39:38.118+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:39:38.141+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:40:08.719+0000] {processor.py:153} INFO - Started process (PID=3444) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:40:08.721+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:40:08.721+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:40:08.721+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:40:08.728+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:40:08.727+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:40:08.728+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:40:08.752+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T16:40:39.537+0000] {processor.py:153} INFO - Started process (PID=3497) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:40:39.538+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:40:39.539+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:40:39.539+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:40:39.546+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:40:39.545+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:40:39.546+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:40:39.569+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T16:41:10.497+0000] {processor.py:153} INFO - Started process (PID=3560) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:41:10.498+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:41:10.500+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:41:10.499+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:41:10.507+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:41:10.506+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:41:10.507+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:41:10.553+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.062 seconds
[2023-09-09T16:41:40.791+0000] {processor.py:153} INFO - Started process (PID=3623) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:41:40.793+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:41:40.793+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:41:40.793+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:41:40.800+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:41:40.800+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:41:40.803+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:41:40.826+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.039 seconds
[2023-09-09T16:42:10.957+0000] {processor.py:153} INFO - Started process (PID=3676) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:42:10.959+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:42:10.959+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:42:10.959+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:42:10.966+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:42:10.965+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:42:10.966+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:42:10.988+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:42:30.678+0000] {processor.py:153} INFO - Started process (PID=3720) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:42:30.679+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:42:30.680+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:42:30.680+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:42:30.689+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:42:30.689+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:42:30.690+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:42:30.718+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.043 seconds
[2023-09-09T16:43:01.325+0000] {processor.py:153} INFO - Started process (PID=3782) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:43:01.327+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:43:01.327+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:43:01.327+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:43:01.342+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:43:01.342+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:43:01.343+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:43:01.384+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.071 seconds
[2023-09-09T16:44:47.922+0000] {processor.py:153} INFO - Started process (PID=40) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:44:47.928+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:44:47.931+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:44:47.931+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:44:47.963+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:44:47.954+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:44:47.968+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:44:48.037+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.151 seconds
[2023-09-09T16:45:18.541+0000] {processor.py:153} INFO - Started process (PID=92) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:45:18.543+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:45:18.543+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:45:18.543+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:45:18.552+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:45:18.551+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:45:18.553+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:45:18.579+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.042 seconds
[2023-09-09T16:45:49.424+0000] {processor.py:153} INFO - Started process (PID=154) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:45:49.425+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:45:49.426+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:45:49.426+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:45:49.433+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:45:49.432+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:45:49.433+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:45:49.457+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.037 seconds
[2023-09-09T16:46:20.223+0000] {processor.py:153} INFO - Started process (PID=207) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:46:20.224+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:46:20.225+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:46:20.225+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:46:20.231+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:46:20.230+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:46:20.232+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:46:20.254+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:46:50.300+0000] {processor.py:153} INFO - Started process (PID=269) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:46:50.301+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:46:50.301+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:46:50.301+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:46:50.308+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:46:50.307+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:46:50.308+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:46:50.331+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:47:20.876+0000] {processor.py:153} INFO - Started process (PID=332) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:47:20.878+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:47:20.879+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:47:20.878+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:47:20.885+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:47:20.884+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:47:20.886+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:47:20.910+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.039 seconds
[2023-09-09T16:47:51.354+0000] {processor.py:153} INFO - Started process (PID=386) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:47:51.355+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:47:51.355+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:47:51.355+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:47:51.362+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:47:51.361+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:47:51.362+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:47:51.385+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:48:21.440+0000] {processor.py:153} INFO - Started process (PID=448) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:48:21.441+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:48:21.442+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:48:21.442+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:48:21.448+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:48:21.447+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:48:21.449+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:48:21.476+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.040 seconds
[2023-09-09T16:48:52.213+0000] {processor.py:153} INFO - Started process (PID=501) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:48:52.214+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:48:52.215+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:48:52.214+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:48:52.221+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:48:52.220+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:48:52.221+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:48:52.243+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.034 seconds
[2023-09-09T16:49:22.915+0000] {processor.py:153} INFO - Started process (PID=564) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:49:22.916+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:49:22.917+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:49:22.916+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:49:22.923+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:49:22.922+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:49:22.923+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:49:22.945+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.034 seconds
[2023-09-09T16:49:53.108+0000] {processor.py:153} INFO - Started process (PID=625) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:49:53.108+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:49:53.109+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:49:53.109+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:49:53.116+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:49:53.114+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:49:53.116+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:49:53.138+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.033 seconds
[2023-09-09T16:50:23.282+0000] {processor.py:153} INFO - Started process (PID=681) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:50:23.284+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:50:23.285+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:50:23.285+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:50:23.291+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:50:23.290+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:50:23.292+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:50:23.314+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T16:50:53.377+0000] {processor.py:153} INFO - Started process (PID=746) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:50:53.378+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:50:53.379+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:50:53.379+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:50:53.385+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:50:53.384+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:50:53.386+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:50:53.408+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.034 seconds
[2023-09-09T16:51:23.488+0000] {processor.py:153} INFO - Started process (PID=799) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:51:23.489+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:51:23.489+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:51:23.489+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:51:23.496+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:51:23.495+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:51:23.496+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:51:23.519+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T16:51:54.235+0000] {processor.py:153} INFO - Started process (PID=861) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:51:54.236+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:51:54.237+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:51:54.237+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:51:54.244+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:51:54.242+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:51:54.244+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:51:54.266+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:52:24.937+0000] {processor.py:153} INFO - Started process (PID=914) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:52:24.938+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:52:24.939+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:52:24.939+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:52:24.946+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:52:24.944+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:52:24.946+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:52:24.968+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:52:55.626+0000] {processor.py:153} INFO - Started process (PID=976) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:52:55.627+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:52:55.628+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:52:55.628+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:52:55.635+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:52:55.633+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:52:55.635+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:52:55.657+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:53:26.198+0000] {processor.py:153} INFO - Started process (PID=1028) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:53:26.199+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:53:26.200+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:53:26.199+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:53:26.207+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:53:26.205+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:53:26.207+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:53:26.231+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.038 seconds
[2023-09-09T16:53:56.836+0000] {processor.py:153} INFO - Started process (PID=1089) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:53:56.837+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:53:56.838+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:53:56.838+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:53:56.845+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:53:56.843+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:53:56.845+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:53:56.867+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.034 seconds
[2023-09-09T16:54:27.131+0000] {processor.py:153} INFO - Started process (PID=1151) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:54:27.148+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:54:27.149+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:54:27.149+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:54:27.174+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:54:27.172+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:54:27.180+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:54:27.245+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.117 seconds
[2023-09-09T16:54:57.438+0000] {processor.py:153} INFO - Started process (PID=1204) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:54:57.439+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:54:57.440+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:54:57.439+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:54:57.446+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:54:57.445+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:54:57.447+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:54:57.469+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:55:27.679+0000] {processor.py:153} INFO - Started process (PID=1267) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:55:27.680+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:55:27.681+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:55:27.681+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:55:27.688+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:55:27.687+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:55:27.688+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:55:27.714+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.039 seconds
[2023-09-09T16:55:57.826+0000] {processor.py:153} INFO - Started process (PID=1320) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:55:57.827+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:55:57.828+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:55:57.827+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:55:57.834+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:55:57.833+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:55:57.834+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:55:57.858+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:56:27.958+0000] {processor.py:153} INFO - Started process (PID=1382) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:56:27.959+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:56:27.960+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:56:27.960+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:56:27.966+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:56:27.965+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:56:27.967+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:56:27.990+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.037 seconds
[2023-09-09T16:56:58.145+0000] {processor.py:153} INFO - Started process (PID=1435) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:56:58.147+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:56:58.147+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:56:58.147+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:56:58.154+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:56:58.153+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:56:58.154+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:56:58.177+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:57:28.227+0000] {processor.py:153} INFO - Started process (PID=1497) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:57:28.228+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:57:28.229+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:57:28.229+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:57:28.235+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:57:28.234+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:57:28.235+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:57:28.258+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T16:57:58.367+0000] {processor.py:153} INFO - Started process (PID=1560) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:57:58.369+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:57:58.370+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:57:58.370+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:57:58.376+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:57:58.376+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:57:58.377+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:57:58.399+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T16:58:28.668+0000] {processor.py:153} INFO - Started process (PID=1613) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:58:28.668+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:58:28.669+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:58:28.669+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:58:28.676+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:58:28.675+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:58:28.676+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:58:28.701+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.038 seconds
[2023-09-09T16:58:58.964+0000] {processor.py:153} INFO - Started process (PID=1675) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:58:58.966+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:58:58.967+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:58:58.966+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:58:58.973+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:58:58.972+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:58:58.973+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:58:58.996+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T16:59:29.082+0000] {processor.py:153} INFO - Started process (PID=1729) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:59:29.084+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:59:29.085+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:59:29.085+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:59:29.092+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:59:29.091+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:59:29.092+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:59:29.138+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.059 seconds
[2023-09-09T16:59:59.238+0000] {processor.py:153} INFO - Started process (PID=1793) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T16:59:59.239+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T16:59:59.240+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:59:59.240+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:59:59.247+0000] {logging_mixin.py:115} INFO - [2023-09-09T16:59:59.246+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T16:59:59.247+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T16:59:59.269+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T17:00:29.632+0000] {processor.py:153} INFO - Started process (PID=1852) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:00:29.636+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:00:29.637+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:00:29.637+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:00:29.653+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:00:29.652+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:00:29.654+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:00:29.697+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.098 seconds
[2023-09-09T17:00:59.879+0000] {processor.py:153} INFO - Started process (PID=1909) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:00:59.880+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:00:59.881+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:00:59.880+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:00:59.888+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:00:59.887+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:00:59.888+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:00:59.910+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T17:01:30.675+0000] {processor.py:153} INFO - Started process (PID=1970) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:01:30.680+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:01:30.684+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:01:30.684+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:01:30.691+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:01:30.690+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:01:30.700+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:01:30.734+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.063 seconds
[2023-09-09T17:02:01.020+0000] {processor.py:153} INFO - Started process (PID=2023) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:02:01.021+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:02:01.022+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:02:01.022+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:02:01.029+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:02:01.028+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:02:01.029+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:02:01.051+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.034 seconds
[2023-09-09T17:02:31.645+0000] {processor.py:153} INFO - Started process (PID=2076) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:02:31.653+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:02:31.653+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:02:31.653+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:02:31.663+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:02:31.662+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:02:31.664+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:02:31.709+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.074 seconds
[2023-09-09T17:03:01.826+0000] {processor.py:153} INFO - Started process (PID=2138) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:03:01.827+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:03:01.828+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:03:01.828+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:03:01.835+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:03:01.834+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:03:01.836+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:03:01.859+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.037 seconds
[2023-09-09T17:03:31.933+0000] {processor.py:153} INFO - Started process (PID=2190) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:03:31.934+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:03:31.934+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:03:31.934+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:03:31.941+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:03:31.940+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    from task.weather_extraction import *
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:03:31.941+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:03:31.963+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.034 seconds
[2023-09-09T17:03:36.198+0000] {processor.py:153} INFO - Started process (PID=2203) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:03:36.199+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:03:36.200+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:03:36.200+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:03:36.209+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:03:36.208+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:03:36.209+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:03:36.232+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.038 seconds
[2023-09-09T17:04:06.275+0000] {processor.py:153} INFO - Started process (PID=2254) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:04:06.277+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:04:06.278+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:04:06.278+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:04:06.286+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:04:06.285+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:04:06.286+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:04:06.310+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.038 seconds
[2023-09-09T17:04:36.425+0000] {processor.py:153} INFO - Started process (PID=2317) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:04:36.426+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:04:36.432+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:04:36.432+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:04:36.467+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:04:36.466+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:04:36.476+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:04:36.529+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.120 seconds
[2023-09-09T17:05:06.675+0000] {processor.py:153} INFO - Started process (PID=2370) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:05:06.676+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:05:06.676+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:05:06.676+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:05:06.683+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:05:06.682+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:05:06.683+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:05:06.705+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T17:05:37.170+0000] {processor.py:153} INFO - Started process (PID=2434) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:05:37.176+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:05:37.177+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:05:37.177+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:05:37.212+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:05:37.187+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:05:37.212+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:05:37.272+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.114 seconds
[2023-09-09T17:06:07.554+0000] {processor.py:153} INFO - Started process (PID=2487) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:06:07.555+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:06:07.556+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:06:07.556+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:06:07.562+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:06:07.561+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:06:07.563+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:06:07.589+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.039 seconds
[2023-09-09T17:08:37.666+0000] {processor.py:153} INFO - Started process (PID=48) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:08:37.696+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:08:37.697+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:08:37.696+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:08:37.758+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:08:37.757+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:08:37.758+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:08:37.849+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.234 seconds
[2023-09-09T17:09:08.792+0000] {processor.py:153} INFO - Started process (PID=101) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:09:08.793+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:09:08.794+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:09:08.793+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:09:08.800+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:09:08.799+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:09:08.800+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:09:08.824+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T17:09:39.425+0000] {processor.py:153} INFO - Started process (PID=154) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:09:39.426+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:09:39.427+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:09:39.427+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:09:39.434+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:09:39.433+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:09:39.435+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:09:39.458+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.037 seconds
[2023-09-09T17:10:09.901+0000] {processor.py:153} INFO - Started process (PID=216) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:10:09.902+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:10:09.903+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:10:09.903+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:10:09.911+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:10:09.910+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:10:09.911+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:10:09.935+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.037 seconds
[2023-09-09T17:10:40.105+0000] {processor.py:153} INFO - Started process (PID=270) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:10:40.106+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:10:40.107+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:10:40.107+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:10:40.114+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:10:40.113+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:10:40.115+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:10:40.137+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T17:11:58.319+0000] {processor.py:153} INFO - Started process (PID=48) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:11:58.371+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:11:58.376+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:11:58.376+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:11:58.438+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:11:58.437+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:11:58.488+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:11:58.684+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.369 seconds
[2023-09-09T17:15:38.950+0000] {processor.py:153} INFO - Started process (PID=50) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:15:38.972+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:15:38.974+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:15:38.973+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:15:39.052+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:15:39.027+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:15:39.058+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:15:39.169+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.248 seconds
[2023-09-09T17:16:09.520+0000] {processor.py:153} INFO - Started process (PID=103) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:16:09.528+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:16:09.532+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:16:09.532+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:16:09.546+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:16:09.542+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:16:09.546+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:16:09.571+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.058 seconds
[2023-09-09T17:16:40.197+0000] {processor.py:153} INFO - Started process (PID=156) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:16:40.198+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:16:40.199+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:16:40.198+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:16:40.205+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:16:40.204+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:16:40.205+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:16:40.227+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.034 seconds
[2023-09-09T17:17:10.611+0000] {processor.py:153} INFO - Started process (PID=219) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:17:10.618+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:17:10.619+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:17:10.619+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:17:10.627+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:17:10.625+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:17:10.627+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:17:10.650+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.043 seconds
[2023-09-09T17:17:41.303+0000] {processor.py:153} INFO - Started process (PID=272) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:17:41.304+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:17:41.305+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:17:41.305+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:17:41.311+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:17:41.310+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:17:41.312+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:17:41.333+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.034 seconds
[2023-09-09T17:18:11.770+0000] {processor.py:153} INFO - Started process (PID=334) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:18:11.770+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:18:11.771+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:18:11.771+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:18:11.778+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:18:11.777+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:18:11.779+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:18:11.804+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.039 seconds
[2023-09-09T17:18:42.706+0000] {processor.py:153} INFO - Started process (PID=396) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:18:42.708+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:18:42.709+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:18:42.708+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:18:42.716+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:18:42.715+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:18:42.717+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:18:42.742+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.039 seconds
[2023-09-09T17:19:13.648+0000] {processor.py:153} INFO - Started process (PID=449) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:19:13.649+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:19:13.650+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:19:13.650+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:19:13.657+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:19:13.656+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:19:13.657+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:19:13.679+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.034 seconds
[2023-09-09T17:19:44.341+0000] {processor.py:153} INFO - Started process (PID=511) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:19:44.342+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:19:44.343+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:19:44.343+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:19:44.349+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:19:44.348+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:19:44.350+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:19:44.372+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.035 seconds
[2023-09-09T17:20:14.944+0000] {processor.py:153} INFO - Started process (PID=565) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:20:14.945+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:20:14.946+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:20:14.946+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:20:14.952+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:20:14.951+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:20:14.953+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:20:14.976+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T17:20:45.818+0000] {processor.py:153} INFO - Started process (PID=627) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:20:45.819+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:20:45.820+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:20:45.820+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:20:45.827+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:20:45.825+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:20:45.827+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:20:45.850+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.036 seconds
[2023-09-09T17:21:15.901+0000] {processor.py:153} INFO - Started process (PID=690) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:21:15.902+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:21:15.903+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:21:15.902+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:21:15.910+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:21:15.908+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:21:15.910+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:21:15.936+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.039 seconds
[2023-09-09T17:21:46.125+0000] {processor.py:153} INFO - Started process (PID=744) to work on /opt/airflow/dags/weather_dag.py
[2023-09-09T17:21:46.126+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2023-09-09T17:21:46.127+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:21:46.127+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:21:46.134+0000] {logging_mixin.py:115} INFO - [2023-09-09T17:21:46.133+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 4, in <module>
    import task.weather_extraction
ModuleNotFoundError: No module named 'task'
[2023-09-09T17:21:46.135+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2023-09-09T17:21:46.162+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.041 seconds
